services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"

  spark-master-1:
    build: .
    container_name: spark-master-1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
      - SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/spark
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_MASTER_URL=spark://spark-master-1:7077,spark-master-2:7077
      - SPARK_DRIVER_HOST=spark-master-1
      - SPARK_DRIVER_PORT=25333
      - OLLAMA_BASE_URL=http://host.docker.internal:11434      
    ports:
      - "8080:8080"    # Expose only this master UI
      - "7077:7077"    # Master RPC port
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      zookeeper:
        condition: service_started
      chromadb:
        condition: service_healthy

  spark-master-2:
    build: .
    container_name: spark-master-2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
      - SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/spark
      - SPARK_PUBLIC_DNS=spark-master-2
      - SPARK_MASTER_URL=spark://spark-master-1:7077,spark-master-2:7077
      - SPARK_DRIVER_HOST=spark-master-1
      - SPARK_DRIVER_PORT=25333
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      zookeeper:
        condition: service_started
      chromadb:
        condition: service_healthy

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-1:7077,spark-master-2:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
      - SPARK_WORKER_WEBUI_PORT=4040
      - SPARK_PUBLIC_DNS=localhost
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    ports:
      - "4040:4040"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      spark-master-2:
        condition: service_started

  spark-worker-2:
    build: .
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-1:7077,spark-master-2:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
      - SPARK_WORKER_WEBUI_PORT=4041
      - SPARK_PUBLIC_DNS=localhost
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    ports:
      - "4041:4041"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      spark-master-2:
        condition: service_started

  spark-worker-3:
    build: .
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-1:7077,spark-master-2:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
      - SPARK_WORKER_WEBUI_PORT=4042
      - SPARK_PUBLIC_DNS=localhost
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    ports:
      - "4042:4042"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      spark-master-2:
        condition: service_started

  chromadb:
    build: ./dockerfile_chromadb
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/data
    environment:
      - CHROMA_SERVER_NO_AUTH=true
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 15s
      timeout: 10s
      retries: 5

  rag-api:
    build:
      context: .
      dockerfile: dockerfile_api
    container_name: rag-api
    ports:
      - "8001:8001"
    environment:
      - EMBEDDING_CHROMA_HOST=chromadb
      - OLLAMA_BASE_URL=http://host.docker.internal:11434      
    command: ["uvicorn", "apps.main:app", "--host", "0.0.0.0", "--port", "8001"]
    depends_on:
      chromadb:
        condition: service_healthy

  streamlit-app:
    build:
      context: .
      dockerfile: dockerfile_streamlit
    container_name: streamlit-app
    ports:
      - "8501:8501"
    environment:
      # Point to the containerized RAG API service
      - API_HOST=rag-api
      - API_PORT=8001
    depends_on:
      rag-api:
        condition: service_started
