services:
  spark:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_LOCAL_IP=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_DRIVER_MEMORY=4g
      - EMBEDDING_CHROMA_HOST=chromadb
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/Users/manoj/projects/python/nyc311-delta-spark/data

  spark-master:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
    volumes:
      - ./data:/Users/manoj/projects/python/nyc311-delta-spark/data

  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G      #<--- adjust accordingly
      - SPARK_WORKER_CORES=4        #<--- adjust accordingly
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EXECUTOR_MEMORY=2G
      - EMBEDDING_CHROMA_HOST=chromadb
    volumes:
      - ./data:/Users/manoj/projects/python/nyc311-delta-spark/data

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - CHROMA_SERVER_NO_AUTH=true # Disable authentication for local development
      - CHROMA_SERVER_HOST=0.0.0.0 # Allow connections from any IP
      - CHROMA_SERVER_PORT=8000
