services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    profiles: [spark, all]
    ports:
      - "2181:2181"

  spark-master-1:
    build:
      context: .
      dockerfile: docker/dockerfile_spark
    container_name: spark-master-1
    env_file:
      - compose.env
    environment:
      - SPARK_MODE=master
    profiles: [spark, all]
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      zookeeper:
        condition: service_started
      chromadb:
        condition: service_healthy

  spark-master-2:
    build:
      context: .
      dockerfile: docker/dockerfile_spark
    container_name: spark-master-2
    env_file:
      - compose.env
    environment:
      - SPARK_MODE=master
    profiles: [spark, all]
    ports:
      - "5055:4040"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      zookeeper:
        condition: service_started
      chromadb:
        condition: service_healthy

  spark-worker-1:
    build:
      context: .
      dockerfile: docker/dockerfile_spark
    container_name: spark-worker-1
    env_file:
      - compose.env
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=4046
    profiles: [spark, all]
    ports:
      - "4046:4046"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      spark-master-2:
        condition: service_started

  spark-worker-2:
    build:
      context: .
      dockerfile: docker/dockerfile_spark
    container_name: spark-worker-2
    env_file:
      - compose.env
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=4047
    profiles: [spark, all]
    ports:
      - "4047:4047"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      spark-master-2:
        condition: service_started

  spark-worker-3:
    build:
      context: .
      dockerfile: docker/dockerfile_spark
    container_name: spark-worker-3
    env_file:
      - compose.env
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_WEBUI_PORT=4048
    profiles: [spark, all]
    ports:
      - "4048:4048"
    volumes:
      - ./data:/opt/bitnami/spark/data
    depends_on:
      spark-master-1:
        condition: service_started
      spark-master-2:
        condition: service_started

  chromadb:
    build:
      context: .
      dockerfile: docker/dockerfile_chromadb
    container_name: chromadb
    profiles: [spark, rag, all]
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/data
    environment:
      - CHROMA_SERVER_NO_AUTH=true
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 15s
      timeout: 10s
      retries: 5

  rag-api:
    build:
      context: .
      dockerfile: docker/dockerfile_api
    container_name: rag-api
    profiles: [rag, all]
    ports:
      - "8001:8001"
    environment:
      - EMBEDDING_CHROMA_HOST=chromadb
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    command: ["uvicorn", "apps.main:app", "--host", "0.0.0.0", "--port", "8001"]
    depends_on:
      chromadb:
        condition: service_healthy

  streamlit-app:
    build:
      context: .
      dockerfile: docker/dockerfile_streamlit
    container_name: streamlit-app
    profiles: [rag, all]
    ports:
      - "8501:8501"
    environment:
      - API_HOST=rag-api
      - API_PORT=8001
    depends_on:
      rag-api:
        condition: service_started
