# Use a slim Python base image for a smaller footprint
FROM python:3.12-slim

# Install curl for downloading JARs
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


# Set the working directory
WORKDIR /app

# Copy the requirements file first to leverage Docker's layer caching
COPY requirements_api.txt .

# Install all Python dependencies
RUN pip install --no-cache-dir -r requirements_api.txt

# Copy the application code into the working directory
COPY ./apps/main.py ./apps/
COPY ./apps/constant ./apps/constant

# Add the application's directory to PYTHONPATH
ENV PYTHONPATH "${PYTHONPATH}:/app"

# Expose the port the app runs on
EXPOSE 8001