# Use a slim Python base image for a smaller footprint
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

COPY requirements/streamlit.txt ./requirements.txt

# Install all Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code and make it importable
COPY ./apps ./apps
COPY log4j2.properties ./apps/log4j2.properties
ENV PYTHONPATH "${PYTHONPATH}:/opt/bitnami/spark/apps"

# Add the application's directory to PYTHONPATH
ENV PYTHONPATH "${PYTHONPATH}:/app"

# Expose the port the app runs on and define the command to run it
EXPOSE 8501
ENTRYPOINT ["streamlit", "run"]
CMD ["apps/streamlit_app_1.py", "--server.port=8501", "--server.headless=true"]
